[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/config'
post_hook = 'pkill -USR1 cava'

[templates.mako]
input_path = '~/.config/matugen/templates/mako'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

#[templates.yazi]
#input_path = '~/.config/matugen/templates/yazi-theme.toml'
#output_path = '~/.config/yazi/theme.toml'

#[templates.swaync]
#input_path = '~/.config/matugen/templates/colors.css'
#output_path = '~/.config/swaync/colors.css'
#post_hook = 'swaync-client -rs'
